---
services:
  unbound:
    container_name: unbound
    environment:
      - S6_READ_ONLY_ROOT=1
    image: ohmer/alpine-unbound
    ports:
      - target: 53
        protocol: udp
        mode: host
      - target: 53
        protocol: tcp
        mode: host
      - target: 8953
        protocol: tcp
        mode: host
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /run:exec
      - /tmp
    volumes:
      - type: bind
        source: config
        target: /etc/unbound
